server:
    port: ${SERVER_PORT}

spring:
    datasource:
        url: jdbc:postgresql://${DATABASE_HOST}:${POSTGRESQL_DATABASE_PORT}/${POSTGRESQL_DATABASE_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
    sql:
        init:
            mode: always
    properties:
        hibernate:
            format_sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}


    cloud:
        azure:
            storage:
                blob:
                    connection-string: ${AZURE_STORAGE_ACCOUNT_ENDPOINT}
                    container-name: ${AZURE_STORAGE_CONTAINER_NAME}
    servlet:
        multipart:
            max-file-size: 1MB
            max-request-size: 10MB

mybatis:
    mapper-locations: classpath:/com/bockerl/snailmember/mapper/**/*.xml

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        path: /swagger-ui.html

spring.data.jpa.repositories.enabled: true
logging:
    level:
        com:
            bockerl:
                snailmember: DEBUG
