server:
    port: ${SERVER_PORT}

spring:
    #    sql:
    #        init:
    #            mode: always
    #    properties:
    #        hibernate:
    #            format_sql: true
    profiles:
        active: dev
    cloud:
        azure:
            storage:
                blob:
                    connection-string: ${AZURE_STORAGE_ACCOUNT_ENDPOINT}
                    container-name: ${AZURE_STORAGE_CONTAINER_NAME}
    servlet:
        multipart:
            max-file-size: 1MB
            max-request-size: 10MB
    kafka:
        bootstrap-servers: ${KAFKA_PORT}
        topic:
            personal-chat: ${KAFKA_TOPIC_NAME_PERSONAL}
            group-chat: ${KAFKA_TOPIC_NAME_GROUP}
        consumer:
            group-id: ${KAFKA_GROUP_ID}
    data:
        #        redis:
        #            sentinel:
        #                master: ${REDIS_MASTER}
        #                nodes:
        #                    - ${REDIS_PORT1}
        #                    - ${REDIS_PORT2}
        #                    - ${REDIS_PORT3}
        mongodb:
            uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@${MONGO_REPLICA_ADDRESS}/${MONGO_DATABASE_NAME}?authSource=snail&replicaSet=rs0&retryWrites=true
            database: ${MONGO_DATABASE_NAME}


springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        path: /swagger-ui.html

logging:
    level:
        org.mongodb.driver: warn
        com:
            bockerl:
                snailmember: DEBUG

